import type { ModelDataResponse } from "../types";

type Props = { data: ModelDataResponse | null };

export function ModelDataPage({ data }: Props) {
  if (!data) return <div className="page-loading">Henter modell- og datastatus…</div>;
  const regime = data.market_regime;
  const validation = data.backtest_validation;
  const walkForward = validation.checks?.find((item) => item.check_id === "rolling_walk_forward");
  const refreshNeedsAttention = data.meta.status !== "fresh" || data.refresh.status !== "success" || Number(data.refresh.last_error_count ?? 0) > 0;
  return <><div className="page-heading"><div><span className="eyebrow">Sporbarhet og validering</span><h1>Modell og data</h1><p>Status for modellen, datagrunnlaget og den fremoverskuende valideringen.</p></div><span className={`data-status ${data.meta.status}`}>{data.meta.message ?? "Data tilgjengelig"}</span></div>
    <section className={`model-action-card ${refreshNeedsAttention ? "attention" : "ok"}`}><span>{refreshNeedsAttention ? "!" : "✓"}</span><div><strong>{refreshNeedsAttention ? "Daily Refresh trenger oppfølging" : "Ingen handling nødvendig"}</strong><p>{refreshNeedsAttention ? "Oppdater analysedata før denne flaten brukes som grunnlag for nye beslutninger." : "Bruk denne siden ved datafeil, etter refresh eller når modellendringer skal valideres – ikke som en daglig arbeidsflate."}</p></div></section>
    <div className="model-status-grid"><article><span>Modellversjon</span><strong>{data.meta.model_version}</strong><small>Produksjonsregler er uendret</small></article><article><span>Daily Refresh</span><strong>{data.refresh.status_label}</strong><small>{data.refresh.updated_at ?? "Tidspunkt mangler"}</small></article><article><span>Markedsregime</span><strong>{String(regime.regime_label ?? "Ukjent")}</strong><small>{String(regime.benchmark_symbol ?? "Benchmark mangler")}</small></article><article><span>Datafeil</span><strong>{data.refresh.last_error_count ?? "–"}</strong><small>Siste refresh</small></article></div>
    <div className="model-detail-grid"><section className="detail-panel"><div className="panel-title"><h2>Modellsnapshots</h2><span>Sporbar historikk</span></div><div className="metric-list"><div><span>Observasjoner</span><strong>{data.snapshots.rows ?? 0}</strong></div><div><span>Snapshotdatoer</span><strong>{data.snapshots.dates ?? 0}</strong></div><div><span>Siste snapshot</span><strong>{data.snapshots.latest_date ?? "–"}</strong></div></div></section><section className="detail-panel"><div className="panel-title"><h2>Discovery Journal</h2><span>{data.discovery_journal.status ?? "Ukjent"}</span></div><div className="metric-list"><div><span>Signaler</span><strong>{data.discovery_journal.rows ?? 0}</strong></div><div><span>Kohorter</span><strong>{data.discovery_journal.cohorts ?? 0}</strong></div><div><span>Siste signal</span><strong>{data.discovery_journal.latest_signal_date ?? "–"}</strong></div></div><p className="model-warning">Ingen konklusjon om meravkastning før valideringskravene er oppfylt.</p></section></div>
    <section className="detail-panel validation-panel"><div className="panel-title"><h2>Backtest og walk-forward</h2><span className={validation.approved ? "positive" : "negative"}>{validation.approved ? "Godkjent" : "Ikke godkjent"}</span></div><div className="metric-list"><div><span>Blokkerende kontroller</span><strong>{validation.blocked_count ?? "–"}</strong></div><div><span>Advarsler</span><strong>{validation.warning_count ?? "–"}</strong></div><div><span>Rolling walk-forward</span><strong>{String(walkForward?.status ?? "Ukjent")}</strong></div></div><p className="model-warning">Historisk fullmodell-backtest brukes ikke som dokumentasjon på meravkastning så lenge valideringen er blokkert.</p></section>
    <section className="detail-panel model-profiles"><div className="panel-title"><h2>Strategiprofiler</h2><span>Eksisterende klassifisering</span></div><div>{data.strategy_profiles.map((item, index) => <article key={String(item.strategy_type ?? index)}><strong>{String(item.strategy_type ?? "Ukjent")}</strong><span>{String(item.style ?? "")}</span><small>{String(item.typical_hold_days ?? "–")} dager · {String(item.preferred_stop_style ?? "")}</small></article>)}</div></section>
  </>;
}
